"""
Created by Ben Kaiser (UNC-Chapel Hill) 2020-08-19

This should take a CSV-formatted astropy table generated by some Gaia DR2 service and then query the 
PanSTARRS places to get the panstarrs photometry and such. Pipe dreams. Pipe dreams. It's probably 1 in 100 
that this script ever actually gets populated.

This also has to be run in Python3 for the record. Python2 is DNR.

This is largely based on the PanSTARRs example Jupyter notebook https://github.com/spacetelescope/notebooks/blob/master/notebooks/MAST/PanSTARRS/PS1_DR2_TAP/PS1_DR2_TAP.ipynb
"""


import numpy as np
from astroquery.gaia import Gaia
import astropy.units as u
import astropy.coordinates as coord
from astropy.table import Table, vstack, Column
import time

 #Use the pyvo library as our client to the data service.
import pyvo as vo

# For resolving objects with tools from MAST
from astroquery.mast import Mast

# For handling ordinary astropy Tables in responses
#from astropy.table import Table

# For displaying and manipulating some types of results
import requests
import astropy
import numpy as np
import pylab
import time
import json
from matplotlib import pyplot as plt

# For calling the object name resolver. Note these are Python 3 dependencies
#import sys
#import http.client as httplib 
#from urllib.parse import quote as urlencode
#from urllib.request import urlretrieve

# To allow display tweaks for wider response tables
#from IPython.core.display import display
#from IPython.core.display import HTML

# suppress unimportant unit warnings from many TAP services
#import warnings
#warnings.filterwarnings("ignore", module="astropy.io.votable.*")
#warnings.filterwarnings("ignore", module="pyvo.utils.xml.elements")
    

input_file=''
start = time.time()


TAP_service = vo.dal.TAPService("http://vao.stsci.edu/PS1DR2/tapservice.aspx")
TAP_service.describe()

TAP_tables = TAP_service.tables
for tablename in TAP_tables.keys():
    if not "tap_schema" in tablename:  
        TAP_tables[tablename].describe()
        print("Columns={}".format(sorted([k.name for k in TAP_tables[tablename].columns ])))
        print("----")
